services:
  app:
    build:
      context: ../../
      dockerfile: devops/docker/app/Dockerfile
    image: smartpromptbox_pro:prod

    env_file:
      - ../../.env

    healthcheck:
      test: ["CMD", "python", "-c", "import app; print('ok')"]
      interval: 10s
      timeout: 3s
      retries: 3

    restart: unless-stopped
