services:
  smartbox-app:
    build:
      context: ../../
      dockerfile: devops/docker/app/Dockerfile.dev

    env_file:
      - ../../.env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test-key}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11}
      DATABASE_URL: ${DATABASE_URL:-sqlite:///db/memory.db}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}

    volumes:
      - ../../:/app:cached
      - db_data:/app/db

    command: python3 -m app.telegram_bot.bot

    healthcheck:
      test: ["CMD", "python", "-c", "import app; print('ok')"]
      interval: 10s
      timeout: 3s
      retries: 3

    restart: unless-stopped

volumes:
  db_data: {}
