services:
  smartbox-app:
    build:
      context: ../../
      dockerfile: devops/docker/app/Dockerfile
    container_name: smartbox-app
    env_file: ../../.env
    environment:
      # CI/տեղում՝ եթե .env չգտնվի, these defaults apply
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test-key}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-test-token}
    volumes:
      - ../../:/app
    healthcheck:
      test: ["CMD", "python", "-c", "import app; print('ok')"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
