from fastapi import FastAPI
from app.routers import youtube_generate, generate

app = FastAPI(
    title="SmartPromptBox Pro 🎵",
    description="Send YouTube links, get lyrics generated by AI 🤖",
    version="1.0.0"
)

# ✅ Registering routers
app.include_router(youtube_generate.router, prefix="/api/youtube", tags=["YouTube Lyrics"])
app.include_router(generate.router, prefix="/api/generate", tags=["Prompt-based Generation"])

@app.get("/")
def root():
    return {"message": "Welcome to SmartPromptBox Pro API 🎤"}