name: Deploy (dry-run demo)

on:
  workflow_dispatch: {}

jobs:
  dry_run:
    name: Ansible dry-run (check mode)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible
        run: pipx install ansible-core
      - name: Dry-run deploy
        run: |
          cd devops/ansible
          ansible-playbook -i inventory/hosts.ini playbooks/deploy.yml --check -v
